### ISSUE TITLE
teks header quiz di mobile pada saat side view keluar dari kotak

### ISSUE THREAD

**Issue by PakeCi** [kacaykeren/kacaykeren.github.io#10]
![0eaf2743-7abc-42df-b80d-6e41cddcd203](https://user-images.githubusercontent.com/101933091/159124476-c4fff133-58fc-4213-98c2-0ffba1a13fd9.jpg)

Itu banh

**Comment by Fermallow** [comment]
kan bener developer ini harusny pas lagi coding webny jgn ngelembur atau mabok
