### ISSUE TITLE
Rumus Lingkaran jadi Rumus persegi

### ISSUE THREAD

**Issue by PakeCi** [kacaykeren/kacaykeren.github.io#14]
![492cb814-2e7f-4e39-aed0-492aa6e539b4](https://user-images.githubusercontent.com/101933091/159125939-8e7b661c-e9cc-449d-8e77-bb66b6a280c9.jpg)

harusnya luasnya pi x r kuadrat banh

**Comment by yahutahugg** [comment]
udah banh
