### ISSUE TITLE
Ada tulisan Kacay. gajelas

### ISSUE THREAD

**Issue by Fermallow** [kacaykeren/kacaykeren.github.io#2]
Banh ada text gakjelas banh
![image](https://user-images.githubusercontent.com/81200868/157470167-31761764-1dd8-42b2-a353-11aaa98be9a8.png)

**Comment by tebekdzn** [comment]
ngakak abiezzzz

**Comment by yahutahugg** [comment]
udah finish ya banh, udah gak ada.
