### ISSUE TITLE
Font di main page blom keganti

### ISSUE THREAD

**Issue by tebekdzn** [kacaykeren/kacaykeren.github.io#3]
# Font header di home page, kalkulator, ama rumus blom keganti
![image](https://user-images.githubusercontent.com/101271755/159122192-62075394-5f49-483e-b2c0-adaffb49df99.png)
# Font source error
![image](https://user-images.githubusercontent.com/101271755/159122211-d67cd57b-5421-473c-9a93-7f8eee190dc2.png)

**Comment by Fermallow** [comment]
Iya banh betul ituh banh developer g bener nih bajh

**Comment by PakeCi** [comment]
developher perlu bobock banh

**Comment by yahutahugg** [comment]
udah ye banh
