### ISSUE TITLE
Link, Header, Tempat

### ISSUE THREAD

**Issue by PakeCi** [kacaykeren/kacaykeren.github.io#4]
wadoo banh

ini link kalkulator sama quiz aneh banh 
![image](https://user-images.githubusercontent.com/101933091/159122505-7424926b-44d5-4636-8b24-8c6e5baa5ef8.png)

sama margin yanh rumuz di hp jadi tatabrakan banh 
![052c037e-f9f0-4006-bc2e-738b6e7a0790](https://user-images.githubusercontent.com/101933091/159122467-f0b9dcf8-3b50-44d1-8bf1-5986be727785.jpg)

hedernya gag di center banh saya kzl liatnya
![image](https://user-images.githubusercontent.com/101933091/159122520-1a37db8f-d687-41a2-96e7-bfe8427d6c2f.png)

heder quiz sama heder hompeg g sama banh
![image](https://user-images.githubusercontent.com/101933091/159122541-2948ce3b-d55b-4109-aa89-5f01894db536.png)
![image](https://user-images.githubusercontent.com/101933091/159122548-cac37d09-1414-45cc-8544-a4885644a6c8.png)

**Comment by tebekdzn** [comment]
> devnya lelah coy 

![image](https://user-images.githubusercontent.com/101271755/159123512-4183bbb3-6f2a-4763-a952-44ee04004f5e.png)

**Comment by yahutahugg** [comment]
KAOkowokwokwokwok
