### ISSUE TITLE
Link home page logo di quiz.html salah directory

### ISSUE THREAD

**Issue by tebekdzn** [kacaykeren/kacaykeren.github.io#5]
![image](https://user-images.githubusercontent.com/101271755/159122301-eac96b22-b915-43c5-8281-fb46c5f3eda2.png)
## ganti `<a href="index.html">KACAY.</a>`  jadi   ` <a href="/index.html">KACAY.</a>` di halaman kuis.

**Comment by Fermallow** [comment]
Tumben nih tbeg niat

**Comment by tebekdzn** [comment]
> Tumben nih tbeg niat
# oiya tentu saja

**Comment by PakeCi** [comment]
> 

Kesambet apa maz

**Comment by yahutahugg** [comment]
udah ye banh
