### ISSUE TITLE
(New feature req) Tambah hover effect di header ama text ber-link

### ISSUE THREAD

**Issue by tebekdzn** [kacaykeren/kacaykeren.github.io#6]
# this is what i mean:
![hover](https://user-images.githubusercontent.com/101271755/159123328-ab779a87-6f90-48af-bbf0-7abba93bdb10.gif)

# or like this:
![hover2](https://user-images.githubusercontent.com/101271755/159123406-491cf4b2-f237-4eaa-982f-9e1c772c9d54.gif)

**Comment by PakeCi** [comment]
nda bisa basa enggres
