### ISSUE TITLE
Tidak ada tombol untuk memilih menu di Kalkulator pada saat di mode perangkat gengam

### ISSUE THREAD

**Issue by Fermallow** [kacaykeren/kacaykeren.github.io#9]
https://user-images.githubusercontent.com/81200868/159124215-522055ba-b556-4e06-a927-19d736681719.mp4

**Comment by Fermallow** [comment]
tuh banh developer g bener banh pasti abis mabok freshtea

**Comment by tebekdzn** [comment]
ngakax abieezz
